name: ""          # e.g. movie-service
image:
  repository: ""   # e.g. srihari0403/movie-service
  tag: latest

replicaCount: 2

healthPath: ""     # e.g. /api/movies/health

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
