apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: production
spec:
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
